name: etmart-app-build-$(Build.BuildId)

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '896bf226-9d8b-4a11-a630-5355ab4490cc'
  imageRepository: 'sabiremartapp1'
  containerRegistry: 'akspractice01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker-compose.yaml'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  Name: devops-agent-01

stages:
- stage: Build
  displayName: 'Emart App Build'
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(Name)
    steps:
    - task: Npm@1
      displayName: 'Install Dependencies'
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/client'

    - task: DockerCompose@0
      displayName: 'Docker Compose Build'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: 'akspractice01.azurecr.io'
        dockerComposeFile: '$(dockerfilePath)'
        projectName: 'emartapp'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'

    - task: DockerCompose@0
      displayName: 'Push Docker Compose Services'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: 'akspractice01.azurecr.io'
        dockerComposeFile: '$(dockerfilePath)'
        projectName: 'emartapp'
        action: 'Push services'
        includeSourceTags: true
     
