# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '896bf226-9d8b-4a11-a630-5355ab4490cc'
  imageRepository: 'sabiremartapp1'
  containerRegistry: 'akspractice01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker-compose.yaml'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  Name: devops-agent-01

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: devops-agent-01
    steps:
    - task: DockerCompose@0
      displayName: dockkercomose build
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: '{"loginServer":"akspractice01.azurecr.io", "id" : "/subscriptions/410c1a95-68f7-4b30-9fdc-964a1658482d/resourceGroups/AKS-Practice/providers/Microsoft.ContainerRegistry/registries/akspractice01"}'
        dockerComposeFile: '**/docker-compose.yaml'
        projectName: 'vprofile'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: '{"loginServer":"akspractice01.azurecr.io", "id" : "/subscriptions/410c1a95-68f7-4b30-9fdc-964a1658482d/resourceGroups/AKS-Practice/providers/Microsoft.ContainerRegistry/registries/akspractice01"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Push services'
        includeSourceTags: true
        includeLatestTag: true
        

        
      
      
