# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3e914b6d-fd13-4129-8a14-6f1dff079db9'
  imageRepository: 'emartappdocker'
  containerRegistry: 'mafacr01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
  Name: devops-agent-01

stages:
- stage: Build
  displayName: Build emart node api and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: devops-agent-01
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'mafacr01'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
